const checklistData={gst:["PAN and Aadhaar","Business constitution / incorporation proof","Principal place of business proof","Bank account details","Photograph and authorised signatory details"],itr:["PAN and Aadhaar","Form 16 / salary or business income records","Bank statements","Investment and deduction proofs","Previous ITR / tax records"],business:["PAN and identity documents","Business address proof","Constitution documents","Banking requirements","Applicable registrations and licences"],audit:["Books of account","Trial balance and ledgers","Bank statements","Tax and GST records","Supporting invoices and vouchers"]};
document.querySelectorAll(".choice").forEach(btn=>btn.addEventListener("click",()=>{const r=btn.dataset.route;const data={tax:["Tax issue","Tell us about your ITR, notice, TDS or planning requirement and the CA team can guide the next step."],gst:["GST assistance","Choose the GST service you need and send a consultation request. We’ll help identify the documents and filing route."],business:["Business setup","Tell us what you are starting and the CA can map registrations, tax and compliance requirements."],accounts:["Accounts support","Get help with bookkeeping, MIS, audit preparation or ongoing accounting." ]}[r];const box=document.getElementById("route-result");box.innerHTML='<h3>'+data[0]+'</h3><p>'+data[1]+'</p><a class="btn light" style="margin-top:16px" href="#contact">Start a request →</a>';box.classList.remove("hidden")}));
const renderChecklist=()=>{const k=document.getElementById("doc-service").value;document.getElementById("checklist").innerHTML=checklistData[k].map(x=>'<li>'+x+'</li>').join("")};document.getElementById("checklist-btn").addEventListener("click",renderChecklist);renderChecklist();
function demoSave(type,data,msg){const key="caDesk_"+type;const old=JSON.parse(localStorage.getItem(key)||"[]");old.unshift({...data,createdAt:new Date().toISOString(),status:"New"});localStorage.setItem(key,JSON.stringify(old));msg.textContent="Received — this demo lead is now visible in the Admin Portal.";setTimeout(()=>msg.textContent="",4500)}
document.getElementById("lead-form").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),data=Object.fromEntries(f.entries());demoSave("leads",data,document.getElementById("lead-msg"));e.target.reset()});
document.getElementById("question-form").addEventListener("submit",e=>{e.preventDefault();const f=new FormData(e.target),data=Object.fromEntries(f.entries());demoSave("questions",data,document.getElementById("question-msg"));e.target.reset()});

const menuBtn=document.querySelector(".menu");
if(menuBtn){const mobileNav=document.createElement("div");mobileNav.className="mobile-nav";mobileNav.innerHTML='<a href="#solutions">Solutions</a><a href="#services">Services</a><a href="#documents">Documents</a><a href="#contact">Contact</a><a href="admin.html">Admin Portal ↗</a>';document.querySelector(".nav").appendChild(mobileNav);menuBtn.addEventListener("click",()=>mobileNav.classList.toggle("open"));mobileNav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>mobileNav.classList.remove("open")));}

const aiFab=document.getElementById("ai-fab"),aiPanel=document.getElementById("ai-panel"),aiClose=document.getElementById("ai-close"),aiMessages=document.getElementById("ai-messages"),aiForm=document.getElementById("ai-form"),aiText=document.getElementById("ai-text");
function aiAdd(text,type){const d=document.createElement("div");d.className="ai-msg "+type;d.textContent=text;aiMessages.appendChild(d);aiMessages.scrollTop=aiMessages.scrollHeight}
function aiAnswer(q){const x=q.toLowerCase();if(x.includes("gst"))return "For GST, the CA may help with registration, returns, reconciliation and notices. If you tell me your business type and turnover situation, I can point you to the relevant service. For an actual filing or notice, speak with the CA.";
if(x.includes("notice"))return "Don't ignore a tax or GST notice. Keep the notice PDF, relevant return/ITR and supporting records ready. Use the consultation form so the CA can review the actual notice.";
if(x.includes("itr")||x.includes("income tax")||x.includes("return"))return "For an ITR, keep PAN, Aadhaar, Form 16 or business income records, bank statements and deduction/investment proofs ready. The correct ITR depends on your income and circumstances.";
if(x.includes("business")||x.includes("company")||x.includes("startup"))return "For a new business, the CA can help map constitution, registrations, GST/TDS and ongoing compliance. Tell us whether it is a proprietorship, partnership, LLP or company.";
if(x.includes("account")||x.includes("book"))return "Accounting support can cover bookkeeping, ledgers, bank records, MIS and audit preparation. The firm can tailor this through the consultation form.";
return "I can help route you to GST, Income Tax, notices, business setup or accounting. Try one of the quick options, or send your question to the CA desk."; }
document.querySelectorAll("[data-ai]").forEach(b=>b.addEventListener("click",()=>{aiAdd(b.dataset.ai,"user");setTimeout(()=>aiAdd(aiAnswer(b.dataset.ai),"bot"),250)}));
aiFab?.addEventListener("click",()=>{aiPanel.classList.toggle("open");aiPanel.setAttribute("aria-hidden",String(!aiPanel.classList.contains("open")));});
aiClose?.addEventListener("click",()=>aiPanel.classList.remove("open"));
aiForm?.addEventListener("submit",e=>{e.preventDefault();const q=aiText.value.trim();if(!q)return;aiAdd(q,"user");aiText.value="";setTimeout(()=>aiAdd(aiAnswer(q),"bot"),300)});


// Self-service tools
const inr=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Math.max(0,n));
function slabTaxNew(income){let t=0;const slabs=[[400000,0],[400000,.05],[400000,.10],[400000,.15],[400000,.20],[400000,.25],[Infinity,.30]];let left=income;for(const [limit,rate] of slabs){const part=Math.min(left,limit);if(part>0)t+=part*rate;left-=part;if(left<=0)break}return t}
function slabTaxOld(income,age){const s=age>=80?[[500000,0],[500000,.20],[Infinity,.30]]:age>=60?[[300000,0],[200000,.05],[500000,.20],[Infinity,.30]]:[[250000,0],[250000,.05],[500000,.20],[Infinity,.30]];let t=0,left=income;for(const [limit,rate] of s){const part=Math.min(left,limit);if(part>0)t+=part*rate;left-=part;if(left<=0)break}return t}
function calculateTax(){const regime=document.getElementById("tax-regime").value;const gross=Math.max(0,Number(document.getElementById("tax-income").value)||0);const deduction=Math.max(0,Number(document.getElementById("tax-deduction").value)||0);let taxable=regime==="old"?Math.max(0,gross-deduction):gross;let tax=regime==="old"?slabTaxOld(taxable,0):slabTaxNew(taxable);let rebate=0;if(regime==="new"&&taxable<=1200000)rebate=Math.min(tax,60000);if(regime==="old"&&taxable<=500000)rebate=Math.min(tax,12500);tax=Math.max(0,tax-rebate);const cess=tax*.04,total=tax+cess;document.getElementById("tax-result").innerHTML='<strong>Estimated tax payable</strong><div class="rate">'+inr(total)+'</div><div>Tax after rebate: '+inr(tax)+' · 4% cess: '+inr(cess)+'</div><small>Taxable income used: '+inr(taxable)+(regime==="old"?" · Old-regime deductions: "+inr(deduction):"")+'</small>'}
document.getElementById("tax-calc")?.addEventListener("click",calculateTax);
const hsnData=[
{keys:["kulfi","ice cream","kulfi"],code:"2105",desc:"Kulfi",rate:"18%"},{keys:["maize seeds","corn seeds"],code:"1005",desc:"Maize of seed quality",rate:"Nil"},{keys:["water purifier","water filter","filter"],code:"8421",desc:"Filters or water purifiers",rate:"18%"},{keys:["lac bangles","shellac bangles","bangles"],code:"7117",desc:"Lac or shellac bangles",rate:"3%"},{keys:["idli dosa batter","dosa batter","idli batter"],code:"2106",desc:"Idli/Dosa batter (food mixes)",rate:"18%"},{keys:["nail polish"],code:"3304",desc:"Nail polish",rate:"28%"},{keys:["wet dates","dates"],code:"0804",desc:"Wet dates",rate:"12%"},{keys:["pet food","dog food","cat food"],code:"2309",desc:"Dog or cat food",rate:"18%"},{keys:["khari","hard butter"],code:"1905",desc:"Khari and hard butters",rate:"18%"},{keys:["khoya","mawa"],code:"0402",desc:"Khoya/Mawa (concentrated milk)",rate:"5%"},{keys:["tamarind fresh"],code:"0810",desc:"Fresh tamarind",rate:"Nil"},{keys:["tamarind dry","dry tamarind"],code:"0813",desc:"Dry tamarind",rate:"12%"},{keys:["hair rubber band","rubber band"],code:"4016",desc:"Hair rubber bands",rate:"28%"},{keys:["carton corrugated","corrugated carton"],code:"4819",desc:"Corrugated paper/paperboard cartons",rate:"12%"}];
function findHSN(){const q=document.getElementById("hsn-query").value.trim().toLowerCase();const box=document.getElementById("hsn-result");if(!q){box.innerHTML="Enter a product name or HSN heading.";return}const clean=q.replace(/\\s/g,"");let hits=hsnData.filter(x=>x.keys.some(k=>q.includes(k)||k.includes(q)));if(/^\\d{4,8}$/.test(clean))hits=hsnData.filter(x=>x.code===clean||clean.startsWith(x.code)||x.code.startsWith(clean));if(!hits.length){box.innerHTML="<strong>No built-in match.</strong><br>Use the official CBIC/GST HSN search for the exact product description and classification." ;return}box.innerHTML=hits.slice(0,4).map(x=>'<div style="margin-bottom:10px"><strong>HSN '+x.code+'</strong> — '+x.desc+'<br><span class="rate">'+x.rate+' GST</span></div>').join("")}
document.getElementById("hsn-search")?.addEventListener("click",findHSN);document.getElementById("hsn-query")?.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();findHSN()}});
let selectedDocs=[];const fileInput=document.getElementById("document-files"),uploadList=document.getElementById("upload-list"),uploadMsg=document.getElementById("upload-msg");function renderUploads(){uploadList.innerHTML=selectedDocs.map((f,i)=>'<div class="upload-item"><span>'+f.name+' · '+Math.round(f.size/1024)+' KB</span><button type="button" data-remove="'+i+'">×</button></div>').join("");uploadList.querySelectorAll("[data-remove]").forEach(b=>b.addEventListener("click",()=>{selectedDocs.splice(Number(b.dataset.remove),1);renderUploads()}))}fileInput?.addEventListener("change",e=>{const incoming=[...e.target.files].filter(f=>f.size<=10*1024*1024);const totalSelected=e.target.files.length;selectedDocs=[...selectedDocs,...incoming];renderUploads();e.target.value="";if(incoming.length<totalSelected)uploadMsg.textContent="Some files were skipped because they exceed 10 MB.";});document.getElementById("upload-send")?.addEventListener("click",()=>{if(!selectedDocs.length){uploadMsg.textContent="Choose at least one document first.";return}const meta=selectedDocs.map(f=>({name:f.name,size:f.size,type:f.type,createdAt:new Date().toISOString()}));localStorage.setItem("caDesk_documentUploads",JSON.stringify(meta));uploadMsg.textContent=meta.length+" document(s) added to this browser session. Connect Firebase Storage for real CA-side uploads.";});
